apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.sql.serviceName }}

spec:
  clusterIP: None

  selector:
    app: sqlserver

  ports:
  - port: {{ .Values.sql.port }}
    targetPort: {{ .Values.sql.port }}