apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: trips-api-monitor
  namespace: default
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - dockertrips

  selector:
    matchLabels:
      app: trips-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s