apiVersion: batch/v1
kind: Job

metadata:
  name: database-backup

spec:
  template:
    spec:
      containers:
      - name: backup
        image: busybox
        command:
        - sh
        - -c
        - echo "Backing up database"

      restartPolicy: Never